### ISSUE TITLE
bot hosting

### ISSUE THREAD

**Issue by acrylic-style** [2b2tjp/2b2t.jp-bot#4]
who will host the 2b2t.jp bot?

**Comment by acrylic-style** [comment]
I invited you @sya-ri to 2b2t.jp Team on Discord, which will make you able to see the bot token.

**Comment by sya-ri** [comment]
thanks <3

**Comment by acrylic-style** [comment]
wait, so who will host the 2b2t.jp bot?

**Comment by sya-ri** [comment]
who is hosting now?

**Comment by acrylic-style** [comment]
me

**Comment by sya-ri** [comment]
if you write the how to install in the README, we will(can) do it here.

**Comment by acrylic-style** [comment]
https://docs.2b2t.jp/#/self-hosting/selfhosting-the-2b2t-jp-bot

**Comment by sya-ri** [comment]
ok, we will do

**Comment by sya-ri** [comment]
i did, so you can stop hosting

**Comment by acrylic-style** [comment]
ok, looks like it's working now
